version: '3.5'

services:
  frontend-example-docker:
    image: jorgeyza/frontend-example-docker
    ports:
      - 5000:5000
    environment:
      - API_URL=http://localhost:8000
  backend-example-docker:
    image: jorgeyza/backend-example-docker
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/mydir/backend-example-docker/logs.txt
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB-NAME=backend-postgres-db
      - DB_PASSWORD=example
      - DB_HOST=db
    depends_on:
      - redis
      - db
  redis:
    image: redis:alpine
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_backend
